# name: python external library
name: quality gateway implementation

on:
  push:
    branches:
      - main

jobs:
  run-python-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install required package
        run: pip install -r requirements.txt

      - name: run test case
        run: pytest --cov==cal --cov-report=term

      # - name: install required library
      #   run: pip install pandas -r requirements.txt

   

      # - name: run python
      #   run: python data.py



